### ISSUE TITLE
send #help messages from zodbot to fedmsg

### ISSUE THREAD

**Issue by nirik** [fedora-infra/supybot-meetbot#13]
https://pagure.io/fedora-infrastructure/issue/4478

= problem =

It'd be awesome to collect #help requests from meetings to feed into something like http://whatcanidoformozilla.org/ (probably filtered/edited by hand), or simply a report of "help needed this week".

= enhancement recommendation =

We'd need:

meeting name
link to the meeting log (for context)
name of person calling for help (for contact info)
the help item itself

Possibly could include current meeting topic, but I think it's better to train people to make their help requests self-sufficient.

**Comment by ryanlerch** [comment]
Meetbot sends fedora messages for help commands.

Not sure if this was added after this RFE was originally filed. but it sends them now.

closing this off
