### ISSUE TITLE
Import VCS history?

### ISSUE THREAD

**Issue by nirik** [fedora-infra/supybot-meetbot#16]
(Moved from old pagure tracker)

A while ago, I imported the upstream Meetbot code from DACS to git, and put it here:

https://pagure.io/meetbot

I noticed the commit history is missing from this repo. Is that something that is valuable? In either case, since there are plans to host our own active fork anyways, I don't think I need to keep my repo around. Let me know if you want it and I can assign admin privileges there, or just delete my repo.

**Comment by ryanlerch** [comment]
ah -- i forked this one from:

https://pagure.io/supybot-meetbot/commits/master

which appeared to be the one in use in production...

**Comment by ryanlerch** [comment]
@nirik just imported the code into this repo now -- so we can remove / delete the old repo.
